tidelift: npm/eslint-plugin-functional
ko_fi: rebeccastevens
custom: https://github.com/eslint-functional/eslint-plugin-functional/blob/main/DONATIONS.md
issuehunt: eslint-functional/eslint-plugin-functional
