name: CI

on:
  workflow_call:

jobs:
  lint_js:
    uses: ./.github/workflows/lint-js.yml
  lint_knip:
    uses: ./.github/workflows/lint-knip.yml
  lint_markdown:
    uses: ./.github/workflows/lint-markdown.yml
  lint_spelling:
    uses: ./.github/workflows/lint-spelling.yml
  lint_prettier:
    uses: ./.github/workflows/lint-prettier.yml
  test:
    uses: ./.github/workflows/test-js.yml
  type_check:
    uses: ./.github/workflows/type-check.yml
