name: Release

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: write

concurrency:
  group: Release
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/prepare

      - name: Build
        run: pnpm run build

      - name: Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
